name: Create VM Workflow

on:
  repository_dispatch:
    types: [create-vm]

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Validate Inputs
        run: |

          VM_NAME="${{ github.event.client_payload.vmName }}"
          VM_SIZE="${{ github.event.client_payload.vmSize }}"

          if [ -z "$VM_NAME" ]; then
            echo "VM Name is missing"
            exit 1
          fi

          if [ -z "$VM_SIZE" ]; then
            echo "VM Size is missing"
            exit 1
          fi

          echo "Validation Successful"

  approval:

    needs: validate

    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:

      - name: Approved
        run: echo "Request Approved Successfully"
